language: c

dist: xenial

sudo: true

python:
  - "2.7"

addons:
  apt:
    packages:
      - libjansson4
      - libsnappy1v5

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - pip2 install --user cpp-coveralls
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - sudo dpkg -i ./deps/linux/libavro23_1.8.2-1_amd64.deb
  - sudo dpkg -i ./deps/linux/libavro-dev_1.8.2-1_amd64.deb

install:
  - luarocks make rockspecs/lua-avro-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

before_script:
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls

script:
  - lua -l luacov -l avro.test -v

after_success:
  - coveralls -b .. -r .. --dump c.report.json
  - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always
