language: c

dist: xenial

sudo: true

python:
  - "2.7"

sudo: false

# addons:
#   apt:
#     packages:
#       - libavro-dev

env:
  matrix:
    - LUA="lua 5.1"
    # - LUA="lua 5.2"
    # - LUA="lua 5.3"
    # - LUA="luajit 2.0"
    # - LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - sudo dpkg -i ./deps/linux/libavro23_1.8.2-1_amd64.deb
  - sudo dpkg -i ./deps/linux/libavro-dev_1.8.2-1_amd64.deb

install:
  - luarocks make rockspecs/lua-avro-scm-0.rockspec

script:
  - lua -l 'avro.test' -v

notifications:
  email:
    on_success: change
    on_failure: always
